%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-nav2-costmap-2d
Version:        1.2.10
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS nav2_costmap_2d package

License:        BSD-3-Clause and Apache-2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-iron-angles
Requires:       ros-iron-geometry-msgs
Requires:       ros-iron-laser-geometry
Requires:       ros-iron-map-msgs
Requires:       ros-iron-message-filters
Requires:       ros-iron-nav-msgs
Requires:       ros-iron-nav2-msgs
Requires:       ros-iron-nav2-util
Requires:       ros-iron-nav2-voxel-grid
Requires:       ros-iron-pluginlib
Requires:       ros-iron-rclcpp
Requires:       ros-iron-rclcpp-lifecycle
Requires:       ros-iron-sensor-msgs
Requires:       ros-iron-std-msgs
Requires:       ros-iron-std-srvs
Requires:       ros-iron-tf2
Requires:       ros-iron-tf2-geometry-msgs
Requires:       ros-iron-tf2-ros
Requires:       ros-iron-tf2-sensor-msgs
Requires:       ros-iron-visualization-msgs
Requires:       ros-iron-ros-workspace
BuildRequires:  ros-iron-ament-cmake
BuildRequires:  ros-iron-angles
BuildRequires:  ros-iron-geometry-msgs
BuildRequires:  ros-iron-laser-geometry
BuildRequires:  ros-iron-map-msgs
BuildRequires:  ros-iron-message-filters
BuildRequires:  ros-iron-nav-msgs
BuildRequires:  ros-iron-nav2-common
BuildRequires:  ros-iron-nav2-msgs
BuildRequires:  ros-iron-nav2-util
BuildRequires:  ros-iron-nav2-voxel-grid
BuildRequires:  ros-iron-pluginlib
BuildRequires:  ros-iron-rclcpp
BuildRequires:  ros-iron-rclcpp-lifecycle
BuildRequires:  ros-iron-sensor-msgs
BuildRequires:  ros-iron-std-msgs
BuildRequires:  ros-iron-std-srvs
BuildRequires:  ros-iron-tf2
BuildRequires:  ros-iron-tf2-geometry-msgs
BuildRequires:  ros-iron-tf2-ros
BuildRequires:  ros-iron-tf2-sensor-msgs
BuildRequires:  ros-iron-visualization-msgs
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-iron-ament-cmake-gtest
BuildRequires:  ros-iron-ament-lint-auto
BuildRequires:  ros-iron-ament-lint-common
BuildRequires:  ros-iron-launch
BuildRequires:  ros-iron-launch-testing
BuildRequires:  ros-iron-nav2-lifecycle-manager
BuildRequires:  ros-iron-nav2-map-server
%endif

%description
This package provides an implementation of a 2D costmap that takes in sensor
data from the world, builds a 2D or 3D occupancy grid of the data (depending on
whether a voxel based implementation is used), and inflates costs in a 2D
costmap based on the occupancy grid and a user specified inflation radius. This
package also provides support for map_server based initialization of a costmap,
rolling window based costmaps, and parameter based subscription to and
configuration of sensor topics.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/iron" \
    -DAMENT_PREFIX_PATH="/opt/ros/iron" \
    -DCMAKE_PREFIX_PATH="/opt/ros/iron" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Sat Aug 24 2024 Steve Macenski <stevenmacenski@gmail.com> - 1.2.10-1
- Autogenerated by Bloom

* Thu May 30 2024 Steve Macenski <stevenmacenski@gmail.com> - 1.2.9-1
- Autogenerated by Bloom

* Thu May 23 2024 Steve Macenski <stevenmacenski@gmail.com> - 1.2.8-1
- Autogenerated by Bloom

* Thu Apr 04 2024 Steve Macenski <stevenmacenski@gmail.com> - 1.2.7-1
- Autogenerated by Bloom

* Tue Jan 23 2024 Steve Macenski <stevenmacenski@gmail.com> - 1.2.6-1
- Autogenerated by Bloom

* Wed Nov 01 2023 Steve Macenski <stevenmacenski@gmail.com> - 1.2.5-2
- Autogenerated by Bloom

