%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-nav2-simple-commander
Version:        1.3.5
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS nav2_simple_commander package

License:        Apache-2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jazzy-action-msgs
Requires:       ros-jazzy-geometry-msgs
Requires:       ros-jazzy-lifecycle-msgs
Requires:       ros-jazzy-nav2-msgs
Requires:       ros-jazzy-rclpy
Requires:       ros-jazzy-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-jazzy-ament-copyright
BuildRequires:  ros-jazzy-ament-flake8
BuildRequires:  ros-jazzy-ament-pep257
%endif

%description
An importable library for writing mobile robot applications in python3

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/jazzy"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Wed Feb 05 2025 steve <stevenmacenski@gmail.com> - 1.3.5-1
- Autogenerated by Bloom

* Fri Dec 13 2024 steve <stevenmacenski@gmail.com> - 1.3.4-1
- Autogenerated by Bloom

* Fri Nov 08 2024 steve <stevenmacenski@gmail.com> - 1.3.3-1
- Autogenerated by Bloom

* Tue Jun 25 2024 steve <stevenmacenski@gmail.com> - 1.3.1-1
- Autogenerated by Bloom

* Tue Jun 25 2024 steve <stevenmacenski@gmail.com> - 1.3.0-2
- Autogenerated by Bloom

